modules1 = [{"id":1,"type":"story","title":{"ru":"Частицы случайности","en":"Particles of Chance","ua":"Частинки випадковості"},
"tags":["философия"],"content":{"ru":"texts/ru/story_1.txt","en":"texts/en/story_1.txt","ua":"texts/ua/story_1.txt"},
"model":"club"},
{"id":2,"type":"experiment","title":{"ru":"Маятник иллюзий","en":"Pendulum of Illusions","ua":"Маятник ілюзій"},
"tags":["физика"],"content":{"ru":"texts/ru/experiment_2.txt","en":"texts/en/experiment_2.txt","ua":"texts/ua/experiment_2.txt"},
"model":"crime"},
{"id":3,"type":"minigame","title":{"ru":"Случайное блуждание","en":"Random Walk","ua":"Випадкове блукання"},
"description":{"ru":"Точка блуждает по плоскости, оставляя след траектории.","en":"A point wanders randomly, leaving a path.","ua":"Точка блукає площиною, залишаючи слід траєкторії."},
"content":{"ru":"games/randomwalk_ru.html","en":"games/randomwalk_en.html","ua":"games/randomwalk_ua.html"},
"model":"game"},
{"id":4,"type":"hint","title":{"ru":"Загадка ветра","en":"Riddle of the Wind","ua":"Загадка вітру"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_4.txt","en":"texts/en/hint_4.txt","ua":"texts/ua/hint_4.txt"},
"model":"snake"},
{"id":5,"type":"story","title":{"ru":"Камень и облако","en":"The Stone and the Cloud","ua":"Камінь і хмара"},
"tags":["природа"],"content":{"ru":"texts/ru/story_5.txt","en":"texts/en/story_5.txt","ua":"texts/ua/story_5.txt"},
"model":"club"},
{"id":6,"type":"experiment","title":{"ru":"Траектория пылинки","en":"Trajectory of a Dust Particle","ua":"Траєкторія порошинки"},
"tags":["хаос"],"content":{"ru":"texts/ru/experiment_6.txt","en":"texts/en/experiment_6.txt","ua":"texts/ua/experiment_6.txt"},
"model":"crime"},
{"id":7,"type":"minigame","title":{"ru":"Спираль Архимеда","en":"Archimedean Spiral","ua":"Спіраль Архімеда"},
"description":{"ru":"При кликах спираль Архимеда нарастает всё дальше и дальше.","en":"Click to grow an Archimedean spiral further and further.","ua":"При кліках спіраль Архімеда розростається все далі й далі."},
"content":{"ru":"games/spiral_ru.html","en":"games/spiral_en.html","ua":"games/spiral_ua.html"},
"model":"game"},
{"id":8,"type":"hint","title":{"ru":"Откровение зеркала","en":"Revelation of the Mirror","ua":"Одкровення дзеркала"},
"tags":["философия"],"content":{"ru":"texts/ru/hint_8.txt","en":"texts/en/hint_8.txt","ua":"texts/ua/hint_8.txt"},
"model":"snake"},
{"id":9,"type":"story","title":{"ru":"Сон муравья","en":"The Ant's Dream","ua":"Сон мурашки"},
"tags":["животные"],"content":{"ru":"texts/ru/story_9.txt","en":"texts/en/story_9.txt","ua":"texts/ua/story_9.txt"},
"model":"club"},
{"id":10,"type":"experiment","title":{"ru":"Бросок тени","en":"Throw of the Shadow","ua":"Кидок тіні"},
"tags":["геометрия"],"content":{"ru":"texts/ru/experiment_10.txt","en":"texts/en/experiment_10.txt","ua":"texts/ua/experiment_10.txt"},
"model":"crime"},
{"id":11,"type":"minigame","title":{"ru":"Круги Лиссажу","en":"Lissajous Figures","ua":"Фігури Ліссажу"},
"description":{"ru":"Колебания по двум осям образуют удивительные фигуры.","en":"Oscillations along two axes form fascinating figures.","ua":"Коливання по двох осях утворюють дивовижні фігури."},
"content":{"ru":"games/lissajous_ru.html","en":"games/lissajous_en.html","ua":"games/lissajous_ua.html"},
"model":"game"},
{"id":12,"type":"hint","title":{"ru":"Загадка времени","en":"Riddle of Time","ua":"Загадка часу"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_12.txt","en":"texts/en/hint_12.txt","ua":"texts/ua/hint_12.txt"},
"model":"snake"},
{"id":13,"type":"story","title":{"ru":"Два берега","en":"Two Shores","ua":"Два береги"},
"tags":["река"],"content":{"ru":"texts/ru/story_13.txt","en":"texts/en/story_13.txt","ua":"texts/ua/story_13.txt"},
"model":"club"},
{"id":14,"type":"experiment","title":{"ru":"Круг случайности","en":"Circle of Chance","ua":"Коло випадковості"},
"tags":["статистика"],"content":{"ru":"texts/ru/experiment_14.txt","en":"texts/en/experiment_14.txt","ua":"texts/ua/experiment_14.txt"},
"model":"crime"},
{"id":15,"type":"minigame","title":{"ru":"Паскаль в точках","en":"Pascal in Dots","ua":"Паскаль у точках"},
"description":{"ru":"Треугольник Паскаля подсвечивается чётными и нечётными числами.","en":"Pascal's triangle highlighted with odd/even pattern.","ua":"Трикутник Паскаля підсвічений парними та непарними числами."},
"content":{"ru":"games/pascal_ru.html","en":"games/pascal_en.html","ua":"games/pascal_ua.html"},
"model":"game"},
{"id":16,"type":"hint","title":{"ru":"Философская нить","en":"Philosophical Thread","ua":"Філософська нитка"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_16.txt","en":"texts/en/hint_16.txt","ua":"texts/ua/hint_16.txt"},
"model":"snake"},
{"id":17,"type":"story","title":{"ru":"Звёздный шум","en":"Star Noise","ua":"Зоряний шум"},
"tags":["космос"],"content":{"ru":"texts/ru/story_17.txt","en":"texts/en/story_17.txt","ua":"texts/ua/story_17.txt"},
"model":"club"},
{"id":18,"type":"experiment","title":{"ru":"Маятник Хаоса","en":"Pendulum of Chaos","ua":"Маятник Хаосу"},
"tags":["динамика"],"content":{"ru":"texts/ru/experiment_18.txt","en":"texts/en/experiment_18.txt","ua":"texts/ua/experiment_18.txt"},
"model":"crime"},
{"id":19,"type":"minigame","title":{"ru":"Спираль простых чисел","en":"Prime Spiral","ua":"Спіраль простих чисел"},
"description":{"ru":"Числа располагаются по спирали, простые подсвечиваются.","en":"Numbers spiral outward, primes are highlighted.","ua":"Числа розташовуються по спіралі, прості підсвічуються."},
"content":{"ru":"games/primespiral_ru.html","en":"games/primespiral_en.html","ua":"games/primespiral_ua.html"},
"model":"game"},
{"id":20,"type":"hint","title":{"ru":"Тайна молчания","en":"Secret of Silence","ua":"Таємниця мовчання"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_20.txt","en":"texts/en/hint_20.txt","ua":"texts/ua/hint_20.txt"},
"model":"snake"},
{"id":21,"type":"story","title":{"ru":"Сердце дождя","en":"Heart of the Rain","ua":"Серце дощу"},
"tags":["природа"],"content":{"ru":"texts/ru/story_21.txt","en":"texts/en/story_21.txt","ua":"texts/ua/story_21.txt"},
"model":"club"},
{"id":22,"type":"experiment","title":{"ru":"Случайный шаг","en":"Random Step","ua":"Випадковий крок"},
"tags":["вероятность"],"content":{"ru":"texts/ru/experiment_22.txt","en":"texts/en/experiment_22.txt","ua":"texts/ua/experiment_22.txt"},
"model":"crime"},
{"id":23,"type":"minigame","title":{"ru":"Клетка Гаусса","en":"Gaussian Grid","ua":"Ґаусова сітка"},
"description":{"ru":"Комплексные числа изображаются как точки на решётке.","en":"Complex numbers visualized as points on a lattice.","ua":"Комплексні числа зображаються як точки на решітці."},
"content":{"ru":"games/gauss_ru.html","en":"games/gauss_en.html","ua":"games/gauss_ua.html"},
"model":"game"},
{"id":24,"type":"hint","title":{"ru":"Загадка света","en":"Riddle of Light","ua":"Загадка світла"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_24.txt","en":"texts/en/hint_24.txt","ua":"texts/ua/hint_24.txt"},
"model":"snake"},
{"id":25,"type":"story","title":{"ru":"Письмо будущему","en":"Letter to the Future","ua":"Лист у майбутнє"},
"tags":["философия"],"content":{"ru":"texts/ru/story_25.txt","en":"texts/en/story_25.txt","ua":"texts/ua/story_25.txt"},
"model":"club"}]
