modules3 = [{"id":51,"type":"story","title":{"ru":"Число в травинке","en":"Number in a Blade of Grass","ua":"Число в травинці"},
"tags":["математика"],"content":{"ru":"texts/ru/story_51.txt","en":"texts/en/story_51.txt","ua":"texts/ua/story_51.txt"},
"model":"dice"},
{"id":52,"type":"experiment","title":{"ru":"Волновая интерференция","en":"Wave Interference","ua":"Хвильова інтерференція"},
"tags":["физика"],"content":{"ru":"texts/ru/experiment_52.txt","en":"texts/en/experiment_52.txt","ua":"texts/ua/experiment_52.txt"},
"model":"snake"},
{"id":53,"type":"minigame","title":{"ru":"Гармонические волны","en":"Harmonic Waves","ua":"Гармонічні хвилі"},
"description":{"ru":"Наложение синусоидальных волн. При клике добавляется новая гармоника.","en":"Superposition of sine waves. On click, a new harmonic is added.","ua":"Накладання синусоїдальних хвиль. При кліку додається нова гармоніка."},
"content":{"ru":"games/waves_ru.html","en":"games/waves_en.html","ua":"games/waves_ua.html"},
"model":"game"},
{"id":54,"type":"hint","title":{"ru":"Загадка числа","en":"Riddle of Number","ua":"Загадка числа"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_54.txt","en":"texts/en/hint_54.txt","ua":"texts/ua/hint_54.txt"},
"model":"crime"},
{"id":55,"type":"story","title":{"ru":"Пыль космоса","en":"Cosmic Dust","ua":"Космічний пил"},
"tags":["астрономия"],"content":{"ru":"texts/ru/story_55.txt","en":"texts/en/story_55.txt","ua":"texts/ua/story_55.txt"},
"model":"dice"},
{"id":56,"type":"experiment","title":{"ru":"Парабола","en":"Parabola","ua":"Парабола"},
"tags":["геометрия"],"content":{"ru":"texts/ru/experiment_56.txt","en":"texts/en/experiment_56.txt","ua":"texts/ua/experiment_56.txt"},
"model":"snake"},
{"id":57,"type":"minigame","title":{"ru":"Лоренц-аттрактор","en":"Lorenz Attractor","ua":"Атрактор Лоренца"},
"description":{"ru":"Хаотическая система Лоренца. Траектория рисуется постепенно.","en":"Chaotic Lorenz system. The trajectory is drawn gradually.","ua":"Хаотична система Лоренца. Траєкторія малюється поступово."},
"content":{"ru":"games/lorenz_ru.html","en":"games/lorenz_en.html","ua":"games/lorenz_ua.html"},
"model":"game"},
{"id":58,"type":"hint","title":{"ru":"Загадка бесконечности","en":"Riddle of Infinity","ua":"Загадка нескінченності"},
"tags":["философия"],"content":{"ru":"texts/ru/hint_58.txt","en":"texts/en/hint_58.txt","ua":"texts/ua/hint_58.txt"},
"model":"crime"},
{"id":59,"type":"story","title":{"ru":"Шёпот атома","en":"Whisper of the Atom","ua":"Шепіт атома"},
"tags":["физика"],"content":{"ru":"texts/ru/story_59.txt","en":"texts/en/story_59.txt","ua":"texts/ua/story_59.txt"},
"model":"dice"},
{"id":60,"type":"experiment","title":{"ru":"Стохастический дождь","en":"Stochastic Rain","ua":"Стохастичний дощ"},
"tags":["вероятность"],"content":{"ru":"texts/ru/experiment_60.txt","en":"texts/en/experiment_60.txt","ua":"texts/ua/experiment_60.txt"},
"model":"snake"},
{"id":61,"type":"minigame","title":{"ru":"Снежинка Серпинского","en":"Sierpinski Snowflake","ua":"Сніжинка Серпінського"},
"description":{"ru":"Фрактальная фигура Серпинского. При клике строится следующий уровень.","en":"Sierpinski fractal figure. On click, the next level is drawn.","ua":"Фрактальна фігура Серпінського. При кліку будується наступний рівень."},
"content":{"ru":"games/sierpinski_ru.html","en":"games/sierpinski_en.html","ua":"games/sierpinski_ua.html"},
"model":"game"},
{"id":62,"type":"hint","title":{"ru":"Загадка скорости","en":"Riddle of Speed","ua":"Загадка швидкості"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_62.txt","en":"texts/en/hint_62.txt","ua":"texts/ua/hint_62.txt"},
"model":"crime"},
{"id":63,"type":"story","title":{"ru":"Музыка чисел","en":"Music of Numbers","ua":"Музика чисел"},
"tags":["математика"],"content":{"ru":"texts/ru/story_63.txt","en":"texts/en/story_63.txt","ua":"texts/ua/story_63.txt"},
"model":"dice"},
{"id":64,"type":"experiment","title":{"ru":"Спираль Архимеда","en":"Archimedean Spiral","ua":"Спіраль Архімеда"},
"tags":["геометрия"],"content":{"ru":"texts/ru/experiment_64.txt","en":"texts/en/experiment_64.txt","ua":"texts/ua/experiment_64.txt"},
"model":"snake"},
{"id":65,"type":"minigame","title":{"ru":"Маятник Хаоса","en":"Chaos Pendulum","ua":"Маятник Хаосу"},
"description":{"ru":"Двойной маятник. Сложное и непредсказуемое движение.","en":"Double pendulum. Complex and unpredictable motion.","ua":"Подвійний маятник. Складний і непередбачуваний рух."},
"content":{"ru":"games/pendulum_ru.html","en":"games/pendulum_en.html","ua":"games/pendulum_ua.html"},
"model":"game"},
{"id":66,"type":"hint","title":{"ru":"Загадка симметрии","en":"Riddle of Symmetry","ua":"Загадка симетрії"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_66.txt","en":"texts/en/hint_66.txt","ua":"texts/ua/hint_66.txt"},
"model":"crime"},
{"id":67,"type":"story","title":{"ru":"Камертон Вселенной","en":"Tuning Fork of the Universe","ua":"Камертон Всесвіту"},
"tags":["музыка"],"content":{"ru":"texts/ru/story_67.txt","en":"texts/en/story_67.txt","ua":"texts/ua/story_67.txt"},
"model":"dice"},
{"id":68,"type":"experiment","title":{"ru":"Электрическое поле","en":"Electric Field","ua":"Електричне поле"},
"tags":["физика"],"content":{"ru":"texts/ru/experiment_68.txt","en":"texts/en/experiment_68.txt","ua":"texts/ua/experiment_68.txt"},
"model":"snake"},
{"id":69,"type":"minigame","title":{"ru":"Граф Лабиринт","en":"Graph Maze","ua":"Граф-лабіринт"},
"description":{"ru":"Случайный граф. При клике создаётся новый лабиринт.","en":"Random graph. On click, a new maze is generated.","ua":"Випадковий граф. При кліку створюється новий лабіринт."},
"content":{"ru":"games/graph_ru.html","en":"games/graph_en.html","ua":"games/graph_ua.html"},
"model":"game"},
{"id":70,"type":"hint","title":{"ru":"Загадка закона","en":"Riddle of the Law","ua":"Загадка закону"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_70.txt","en":"texts/en/hint_70.txt","ua":"texts/ua/hint_70.txt"},
"model":"crime"},
{"id":71,"type":"story","title":{"ru":"Звёздный интеграл","en":"Star Integral","ua":"Зоряний інтеграл"},
"tags":["математика"],"content":{"ru":"texts/ru/story_71.txt","en":"texts/en/story_71.txt","ua":"texts/ua/story_71.txt"},
"model":"dice"},
{"id":72,"type":"experiment","title":{"ru":"Падающий шар","en":"Falling Ball","ua":"Падаючий м’яч"},
"tags":["физика"],"content":{"ru":"texts/ru/experiment_72.txt","en":"texts/en/experiment_72.txt","ua":"texts/ua/experiment_72.txt"},
"model":"snake"},
{"id":73,"type":"minigame","title":{"ru":"Мост Эйлера","en":"Euler Bridge","ua":"Міст Ейлера"},
"description":{"ru":"Нарисуйте граф и попробуйте пройти по всем рёбрам не отрывая карандаш.","en":"Draw a graph and try to walk all edges without lifting the pencil.","ua":"Намалюйте граф і спробуйте пройти всі ребра, не відриваючи олівець."},
"content":{"ru":"games/euler_ru.html","en":"games/euler_en.html","ua":"games/euler_ua.html"},
"model":"game"},
{"id":74,"type":"hint","title":{"ru":"Загадка порядка","en":"Riddle of Order","ua":"Загадка порядку"},
"tags":["мысль"],"content":{"ru":"texts/ru/hint_74.txt","en":"texts/en/hint_74.txt","ua":"texts/ua/hint_74.txt"},
"model":"crime"},
{"id":75,"type":"story","title":{"ru":"Библиотека формул","en":"Library of Formulas","ua":"Бібліотека формул"},
"tags":["философия"],"content":{"ru":"texts/ru/story_75.txt","en":"texts/en/story_75.txt","ua":"texts/ua/story_75.txt"},
"model":"dice"}]
