modules4 = [{"id":76,"type":"story","title":{"ru":"Дверь без ручки","en":"Door Without a Handle","ua":"Двері без ручки"},
"tags":["философия"],"content":{"ru":"texts/ru/story_76.txt","en":"texts/en/story_76.txt","ua":"texts/ua/story_76.txt"},
"model":"snake"},
{"id":77,"type":"experiment","title":{"ru":"Закон больших чисел","en":"Law of Large Numbers","ua":"Закон великих чисел"},
"tags":["математика","вероятность"],"content":{"ru":"texts/ru/experiment_77.txt","en":"texts/en/experiment_77.txt","ua":"texts/ua/experiment_77.txt"},
"model":"club"},
{"id":78,"type":"minigame","title":{"ru":"Снежный фрактал","en":"Snow Fractal","ua":"Сніжний фрактал"},
"description":{"ru":"Кривая Коха. При клике строится новый уровень фрактала.","en":"Koch curve. On click, a new fractal level is drawn.","ua":"Крива Коха. При кліку будується новий рівень фракталу."},
"content":{"ru":"games/koch_ru.html","en":"games/koch_en.html","ua":"games/koch_ua.html"},
"model":"game"},
{"id":79,"type":"hint","title":{"ru":"Порог","en":"Threshold","ua":"Поріг"},
"tags":["афоризм"],"content":{"ru":"texts/ru/hint_79.txt","en":"texts/en/hint_79.txt","ua":"texts/ua/hint_79.txt"},
"model":"dice"},
{"id":80,"type":"story","title":{"ru":"Лестница в небо","en":"Stairway to Heaven","ua":"Сходи в небо"},
"tags":["философия"],"content":{"ru":"texts/ru/story_80.txt","en":"texts/en/story_80.txt","ua":"texts/ua/story_80.txt"},
"model":"snake"},
{"id":81,"type":"experiment","title":{"ru":"Хаос маятника","en":"Pendulum Chaos","ua":"Хаос маятника"},
"tags":["физика","хаос"],"content":{"ru":"texts/ru/experiment_81.txt","en":"texts/en/experiment_81.txt","ua":"texts/ua/experiment_81.txt"},
"model":"club"},
{"id":82,"type":"story","title":{"ru":"Колодец памяти","en":"Memory Well","ua":"Криниця пам’яті"},
"tags":["философия"],"content":{"ru":"texts/ru/story_82.txt","en":"texts/en/story_82.txt","ua":"texts/ua/story_82.txt"},
"model":"crime"},
{"id":83,"type":"minigame","title":{"ru":"Пифагорово дерево","en":"Pythagoras Tree","ua":"Дерево Піфагора"},
"description":{"ru":"Рекурсивное бинарное дерево. При клике добавляется новый уровень.","en":"Recursive binary tree. On click, a new branch level is added.","ua":"Рекурсивне бінарне дерево. При кліку додається новий рівень."},
"content":{"ru":"games/tree_ru.html","en":"games/tree_en.html","ua":"games/tree_ua.html"},
"model":"game"},
{"id":84,"type":"hint","title":{"ru":"Мост","en":"Bridge","ua":"Міст"},
"tags":["афоризм"],"content":{"ru":"texts/ru/hint_84.txt","en":"texts/en/hint_84.txt","ua":"texts/ua/hint_84.txt"},
"model":"snake"},
{"id":85,"type":"story","title":{"ru":"Тень числа","en":"Shadow of a Number","ua":"Тінь числа"},
"tags":["философия","математика"],"content":{"ru":"texts/ru/story_85.txt","en":"texts/en/story_85.txt","ua":"texts/ua/story_85.txt"},
"model":"club"},
{"id":86,"type":"experiment","title":{"ru":"Фрактал Мандельброта","en":"Mandelbrot Fractal","ua":"Фрактал Мандельброта"},
"tags":["математика","визуализация"],"content":{"ru":"texts/ru/experiment_86.txt","en":"texts/en/experiment_86.txt","ua":"texts/ua/experiment_86.txt"},
"model":"crime"},
{"id":87,"type":"story","title":{"ru":"Комната с зеркалами","en":"Room of Mirrors","ua":"Кімната з дзеркалами"},
"tags":["философия"],"content":{"ru":"texts/ru/story_87.txt","en":"texts/en/story_87.txt","ua":"texts/ua/story_87.txt"},
"model":"dice"},
{"id":88,"type":"minigame","title":{"ru":"Случайные частицы","en":"Random Particles","ua":"Випадкові частинки"},
"description":{"ru":"Броуновское движение. Частицы двигаются случайным образом.","en":"Brownian motion. Particles move randomly.","ua":"Броунівський рух. Частинки рухаються випадковим чином."},
"content":{"ru":"games/particles_ru.html","en":"games/particles_en.html","ua":"games/particles_ua.html"},
"model":"game"},
{"id":89,"type":"hint","title":{"ru":"Ключ","en":"Key","ua":"Ключ"},
"tags":["афоризм"],"content":{"ru":"texts/ru/hint_89.txt","en":"texts/en/hint_89.txt","ua":"texts/ua/hint_89.txt"},
"model":"club"},
{"id":90,"type":"story","title":{"ru":"Сад вероятностей","en":"Garden of Probabilities","ua":"Сад ймовірностей"},
"tags":["философия","вероятность"],"content":{"ru":"texts/ru/story_90.txt","en":"texts/en/story_90.txt","ua":"texts/ua/story_90.txt"},
"model":"crime"},
{"id":91,"type":"experiment","title":{"ru":"Музыка чисел","en":"Music of Numbers","ua":"Музика чисел"},
"tags":["математика","музыка"],"content":{"ru":"texts/ru/experiment_91.txt","en":"texts/en/experiment_91.txt","ua":"texts/ua/experiment_91.txt"},
"model":"dice"},
{"id":92,"type":"story","title":{"ru":"Звезда и пыль","en":"Star and Dust","ua":"Зірка і пил"},
"tags":["философия","космос"],"content":{"ru":"texts/ru/story_92.txt","en":"texts/en/story_92.txt","ua":"texts/ua/story_92.txt"},
"model":"snake"},
{"id":93,"type":"minigame","title":{"ru":"Живая спираль","en":"Living Spiral","ua":"Жива спіраль"},
"description":{"ru":"Спираль растёт и изменяется при клике.","en":"Spiral grows and changes on click.","ua":"Спіраль росте та змінюється при кліку."},
"content":{"ru":"games/spiral_ru.html","en":"games/spiral_en.html","ua":"games/spiral_ua.html"},
"model":"game"},
{"id":94,"type":"hint","title":{"ru":"Ветер","en":"Wind","ua":"Вітер"},
"tags":["афоризм"],"content":{"ru":"texts/ru/hint_94.txt","en":"texts/en/hint_94.txt","ua":"texts/ua/hint_94.txt"},
"model":"crime"},
{"id":95,"type":"story","title":{"ru":"Письмо из будущего","en":"Letter from the Future","ua":"Лист із майбутнього"},
"tags":["философия","время"],"content":{"ru":"texts/ru/story_95.txt","en":"texts/en/story_95.txt","ua":"texts/ua/story_95.txt"},
"model":"dice"},
{"id":96,"type":"experiment","title":{"ru":"Клеточный автомат","en":"Cellular Automaton","ua":"Клітинний автомат"},
"tags":["математика","жизнь"],"content":{"ru":"texts/ru/experiment_96.txt","en":"texts/en/experiment_96.txt","ua":"texts/ua/experiment_96.txt"},
"model":"snake"},
{"id":97,"type":"story","title":{"ru":"Лаборатория снов","en":"Dream Laboratory","ua":"Лабораторія снів"},
"tags":["философия"],"content":{"ru":"texts/ru/story_97.txt","en":"texts/en/story_97.txt","ua":"texts/ua/story_97.txt"},
"model":"club"},
{"id":98,"type":"minigame","title":{"ru":"Клеточный автомат","en":"Cellular Automaton","ua":"Клітинний автомат"},
"description":{"ru":"Правила Конвея: жизнь и смерть клеток.","en":"Conway's rules: life and death of cells.","ua":"Правила Конвея: життя і смерть клітин."},
"content":{"ru":"games/life_ru.html","en":"games/life_en.html","ua":"games/life_ua.html"},
"model":"game"},
{"id":99,"type":"hint","title":{"ru":"Окно","en":"Window","ua":"Вікно"},
"tags":["афоризм"],"content":{"ru":"texts/ru/hint_99.txt","en":"texts/en/hint_99.txt","ua":"texts/ua/hint_99.txt"},
"model":"dice"},
{"id":100,"type":"story","title":{"ru":"Океан времени","en":"Ocean of Time","ua":"Океан часу"},
"tags":["философия","время"],"content":{"ru":"texts/ru/story_100.txt","en":"texts/en/story_100.txt","ua":"texts/ua/story_100.txt"},
"model":"snake"}]
